DROP TABLE dm_article;

CREATE TABLE dm_article (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    presentation_image VARCHAR(255),
    title VARCHAR(100) NOT NULL,
    chapo VARCHAR(350) NOT NULL,
    fields JSON NOT NULL,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dm_travefy_trip (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    travefy_trip_id VARCHAR(31) NOT NULL UNIQUE
);